### ISSUE TITLE
the cross dataset test problem

### ISSUE THREAD

**Issue by Z9RO** [zwx8981/BIQA_project#1]
Hello!
I think the method proposed in this article is very novel.
I want to train the model on the LIVE dataset and test on TID2013. However,they have different label.(dmos for LIVE,mos for TID2013) I am not very familiar with matlab, so can you tell me how to convert these labels

**Comment by zwx8981** [comment]
@Z9RO Hi, actually you can directly train the model using original labels. For your example, LIVE uses DMOS (higher means worse quality) while TID2013 uses MOS (higher means better quality),  you can simply train on LIVE with DMOS. When you test on TID2013, you can simply compute the absolute value of SRCC and PLCC as the final results.

**Comment by Z9RO** [comment]
Thanks, but I found the range of those datasets' value is different, LIVE is about [0,100], and TID2013 is about [0,10]. Do you have the exact range of those datasets? (I search the Internet and still don't find LIVEMD's and LIVEChallenge's)

**Comment by zwx8981** [comment]
@Z9RO I normalize subjective quality scores in all datasets into the same range for convenience.  The range of both LIVEMD and LIVEChallenge are [0,100]

**Comment by Z9RO** [comment]
Thanks, it's very useful to me
