### ISSUE TITLE
Error in vl_imreadjpeg() 

### ISSUE THREAD

**Issue by Doooooris** [zwx8981/BIQA_project#10]
大神你好
我在重新训练 model 的时候, 在 imdb_get_batch_bcnn.m line 70 im = vl_imreadjpeg(images,'numThreads', opts(i).numThreads) 发现了error, MATLAB 没有给出任何的error message，请问您知道这是为什么吗？
Dataset: LIVE release2 (bmp image)
系统：WINDOWS 10

        if fetch
            im = vl_imreadjpeg(images,'numThreads', opts(i).numThreads) ;
        else
            im = images ;
        end

特意检查过images的path修改后是正确的，但不知道为什么跑vl_imreadjpeg的时候程序throw error

**Comment by zwx8981** [comment]
@Doooooris  可以参考下这个https://github.com/vlfeat/matconvnet/issues/1025
