### ISSUE TITLE
Wrong use of vl_argparse

### ISSUE THREAD

**Issue by Nirvana-feng** [zwx8981/BIQA_project#12]
Hello author, when I trained run_exp.m according to your steps, I found that "vl_argparse" was wrong. How should I solve this problem?
![image](https://user-images.githubusercontent.com/67857885/144812126-1a86ba14-352c-4939-b101-b9527533bc22.png)

**Comment by zwx8981** [comment]
This problem is mainly related to MatConvNet, which I haven't used for a long time. I am sorry I can't help you.

**Comment by Nirvana-feng** [comment]
Thank you, the problem has just been solved. The problem with the function call is that there is a function with the same name
