### ISSUE TITLE
您好，看到您的一些关于图像质量评价的介绍，想问您个问题，就是BLIINDS-II无参考的指标，我在github上复现了几个matlab的代码，文章中介绍BLIINDS-II越大表明图像质量越好，但是我复现的代码结果是相反的，请问您有这个BLIINDS-II代码吗？

### ISSUE THREAD

**Issue by LXX230** [zwx8981/BIQA_project#13]

**Comment by zwx8981** [comment]
@LXX230 越大越好还是越小越好取决于你的模型在什么数据集上训练。BLIINDS-II如果是在LIVE上训练的，那就是越小越好，因为用的标签是DMOS，不是MOS，代码直接用他们官方的就行，我没有保存。

**Comment by LXX230** [comment]
明白，谢谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月24日(星期一) 下午4:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zwx8981/DBCNN] 您好，看到您的一些关于图像质量评价的介绍，想问您个问题，就是BLIINDS-II无参考的指标，我在github上复现了几个matlab的代码，文章中介绍BLIINDS-II越大表明图像质量越好，但是我复现的代码结果是相反的，请问您有这个BLIINDS-II代码吗？ (Issue #13)





 
@LXX230 越大越好还是越小越好取决于你的模型在什么数据集上训练。BLIINDS-II如果是在LIVE上训练的，那就是越小越好，因为用的标签是DMOS，不是MOS。
