### ISSUE TITLE
Which model should I use to test on the waterloo dataset?

### ISSUE THREAD

**Issue by Xiaocong6** [zwx8981/BIQA_project#4]
hi~thanks very much for your excellent work. I have encountered some confusion and need your help.
You mentioned that in the paper "retrain the S-CNN stream using distorted images generated
from PASCAL VOC 2012 only to ensure the independence of image content between training and testing". Which database do you use when fine-tuning the DB-CNN?
Whether the models under the folder "models" use the waterloo dataset when training S-CNN? I want to test the results on waterloo, which model should I use?
Thanks!

**Comment by zwx8981** [comment]
@Xiaocong6 Hi, the folder "models" contains training-testing split files for each database. The scnn.mat under the 'data/models' folder is trained using the combination of Waterloo and PASCAL as we mentioned in the paper. The model used for Waterloo experiments is not released in this repo.

**Comment by Xiaocong6** [comment]
Thanks!
I am not familiar with Matlab. I want to ask, if I want to use the models your provided to test the results on my own dataset, which file should I run?

**Comment by zwx8981** [comment]
@Xiaocong6 You can train a model on a dataset by running run_exp.m first, then you can use the trained model to test on your dataset. See the demo.m for a simple demo of predicting the quality score of an input image.

**Comment by Xiaocong6** [comment]
Thanks!
Whick dataset is used to train the model used for Waterloo experiments?

**Comment by zwx8981** [comment]
@Xiaocong6 For fair comparison, we train the model on the LIVE dataset for Waterloo experiments.

**Comment by Xiaocong6** [comment]
Thank you very much! I got it.
