### ISSUE TITLE
Can your provide a link to download the Live Challenge?

### ISSUE THREAD

**Issue by Xiaocong6** [zwx8981/BIQA_project#5]
Hi, ^_^. I'm here again.
I can't open the link 'https://www.cs.utexas.edu/%E2%88%BCdeepti/ChallengeDB.zip'.
![图片](https://user-images.githubusercontent.com/44869509/60593862-3d637080-9dd6-11e9-9381-a308221d6ffa.png)

Can you help me?

**Comment by zwx8981** [comment]
@Xiaocong6 https://live.ece.utexas.edu/research/ChallengeDB/index.html

**Comment by Xiaocong6** [comment]
Does it need vpn to open this link? 
I can't open 'THIS' and 'THIS FORM'.
![图片](https://user-images.githubusercontent.com/44869509/60637360-bdc4b880-9e4c-11e9-8b06-504f09bf379b.png)

**Comment by zwx8981** [comment]
@Xiaocong6 Yes, it needs VPN. If you use baiduyun, you can download it from:
https://pan.baidu.com/s/1DhLioyHy0AZ24ZAPZf6TSw  
code: cp48 
unzip passward: Chall3nGeXt3nDd

**Comment by Xiaocong6** [comment]
Thanks!!! You are so kind!!!
