### ISSUE TITLE
error finding a file 

### ISSUE THREAD

**Issue by SheydaGhb** [zwx8981/BIQA_project#7]
when I run the code I get this error 

train: epoch 01:   1/ 78:Error using load
Unable to read file 'data\checkgpu\live-seed-01\nonftbcnn\bcnn_nonft_00003'. No such file or directory.

could you please help me? how is this file created?

**Comment by zwx8981** [comment]
Which file did you run?

**Comment by SheydaGhb** [comment]
I run "run_exp.m" 

I have set modela= path of vgg16 and modelb = path of scnn and also  set useGPU =1 (originaly it was 2) in  "run_experiments_bcnn_train.m" in BCNN folder, otherwise I get error

I want to train it on LIVE2 so dataset is also added . 

as far as I understood there is no " checkgpu\live-seed-01\nonftbcnn" folder and it will be made during the process but suddenly it says it can't find "bcnn_nonft_00003" file too, i think code fails to create it I don't know why . thanks
