### ISSUE TITLE
where can I found the SCNN labels

### ISSUE THREAD

**Issue by voyager0003** [zwx8981/BIQA_project#9]
Appreicate for sharing your great work first!
But I really wonder where can I found the SCNN labels. In the paper, you said there are 125 labels, and in the matlab distortion dir, there is 8 kinds of distortion and each has 5 levels. so there is 40 lables? correct me if i am wrong

**Comment by zwx8981** [comment]
@vegetable09 Hi, there are only 39 classess. 7 types with 5 levels and 2 types with 2 levels.

**Comment by voyager0003** [comment]
THX for reply, I want to confirm which 2 types is with 2 levels.

In readme, There is 9 types:
1, Gaussian Blur
2, White Noise
3, JPEG Compression
4, JPEG2000 Compression
5, Contrast Change
6, Pink Noise
7, Image Color Quantization with Dither
8, Over-Exposure
9, Under-Exposure

level is a specified degradation level range in 1~5.
seed should be fixed to be 1.

**Comment by zwx8981** [comment]
over-exposure and under-exposure



发自我的iPhone


------------------ Original ------------------

**Comment by voyager0003** [comment]
好的！结合论文图2，我知道了，谢谢！
